### ISSUE TITLE
wxml格式化

### ISSUE THREAD

**Issue by nailao** [wx-minapp/minapp-vscode#1]
请问这个格式化是调用vscode本身的格式化，还是别的? 我想忽略text标签，一格式化，text全换行了，希望有个配置能设置

**Comment by qiu8310** [comment]
谢谢反馈，格式化是 minapp 插件内部做的，不是 vscode 的功能。

你说的那个忽略text标签格式化问题，其实配置早就写了，好像一直忘记暴露出来，刚加上了。

更新到 1.7.2，配置 `minapp-vscode.reserveTags = ["text"]` 即可！

**Comment by nailao** [comment]
<view class="desc">请输入你当前绑定的手机号码<text>138******00</text></view>

我是希望这种也能不被格式化掉。

**Comment by qiu8310** [comment]
这个也不太好实现，另外即使格式化也不影响布局吧，text标签格式化后可能影响布局

**Comment by anran758** [comment]
有时候为了简洁，喜欢额外空一行。这样读代码的时候不会因为太紧凑而一眼找不到想看到的部分。这个能暴露出不格式化的配置吗？

**Comment by qiu8310** [comment]
@anran758  没有实现你说的功能，哪些空行应该保留，哪些空行应该删除好难决断

**Comment by CaTmmao** [comment]
> @anran758 没有实现你说的功能，哪些空行应该保留，哪些空行应该删除好难决断

我今天也遇到这个问题。。可以参考下[这个项目](https://github.com/beautify-web/js-beautify)的解决方式，感觉还是挺好的。
不过没事，我先用其他格式化插件凑合了
```
"max_preserve_newlines": 1, // 最多可以保留几个空行
"preserve_newlines": true, // 是否允许保留空行
```
