### ISSUE TITLE
[community]: 插件用户交流方式征集

### ISSUE THREAD

**Issue by iChenLei** [wx-minapp/minapp-vscode#102]
<p align="center" ><img src="https://raw.githubusercontent.com/wx-minapp/minapp-vscode/master/res/icon.png" width="100px"></p>

> 前言: 感谢ZhongLei Qiu开发了这个优秀的小程序VSCode插件，在停止更新两年多之后由Lei Chen接过开发迭代的任务

|    version  |   Last Updated    |
| ------- | ------- |
|  2.3.0 | 18 hours ago |
| 2.2.2 |  8/1/2019 |

随着插件的安装量持续增长，我们意识到在中国有很多小程序开发从业者在使用这个插件，一直以来插件维护者都是通过issue和用户交流沟通成本略高，现在向所有用户征集更加接地气的交流方式！

微信 / 飞书 / 钉钉 / Gitter / Github Disscussion / QQ 等, 说出你的建议, 非常感谢！

**Comment by MaoXuKun** [comment]
微信或者钉钉

**Comment by iChenLei** [comment]
已决定使用钉钉群交流
