### ISSUE TITLE
prettyHtml format error: Cannot find module 'prettier'

### ISSUE THREAD

**Issue by MaoXuKun** [wx-minapp/minapp-vscode#103]
**如何复现:**

步骤1:
更新插件版本到2.3.1

步骤2: 
设置插件配置
  "minapp-vscode.wxmlFormatter": "prettyHtml", // 指定格式化工具
  "minapp-vscode.prettyHtml": {
    // prettyHtml 默认配置
    "useTabs": false,
    "tabWidth": 2,
    "printWidth": 200,
    "singleQuote": false,
    "usePrettier": true,
    "wrapAttributes": true, // 设置成 true 强制属性换行
    "sortAttributes": true
  }

步骤3:
打开任意 wxml 文件进行保存

**期望的表现:**
正常格式化 wxml 文件

**实际的表现:**
VS Code 右下角报错 prettyHtml format error: Cannot find module 'prettier'

**插件运行环境**

- `插件版本`: 2.3.1
- `VSCode版本`:1.59.1
- `操作系统(非必须)`:windows 10

**Comment by iChenLei** [comment]
https://github.com/wx-minapp/minapp-vscode/compare/v2.2.2...v2.3.1 

这是最新版本和两年前的2.2.2版本代码diff对比, 没看出来问题，老版本运行正常吗？ 问题我可以复现，最近几天修一下

**Comment by MaoXuKun** [comment]
插件回滚到 2.2.2 版本运行正常

**Comment by scshsy** [comment]
同遇到 
回滚到2.2.2正常~

**Comment by iChenLei** [comment]
问题还是没解决，给我点时间，谢谢大家

**Comment by iChenLei** [comment]
@scshsy @MaoXuKun 麻烦更新到最新版本，应该已经修复了就反馈，具体PR可见 #105

**Comment by MaoXuKun** [comment]
升级到 v2.3.2 版本此问题依旧存在

**Comment by MaoXuKun** [comment]
升级到 v2.3.3 此问题已修复，感谢大佬
