### ISSUE TITLE
微信开发者工具是不是不能装?

### ISSUE THREAD

**Issue by swearl** [wx-minapp/minapp-vscode#112]
安装时弹出vscode版本不兼容的提示....

![图片](https://user-images.githubusercontent.com/469084/133573747-fba12071-f90a-42cb-847a-88817c15df7e.png)

**Comment by iChenLei** [comment]
微信小程序IDE内嵌的VSCode版本是`1.52.0`,我们插件最小支持版本是 `1.59.1`
https://github.com/wx-minapp/minapp-vscode/blob/ec4fdbf07e7ee91d30a738146ffe94c975911369/package.json#L45
