### ISSUE TITLE
是否有兴趣支持一下mpx框架

### ISSUE THREAD

**Issue by sky-admin** [wx-minapp/minapp-vscode#13]
单文件后缀名.mpx
框架介绍：https://github.com/didi/mpx
文档：https://didi.github.io/mpx/
如有精力和兴趣支持一波，非常感谢。

**Comment by qiu8310** [comment]
可以的，如果可能的话，可以帮我更新下这个文件（主要是关于 mpx 支持的模板上的一些特殊属性或组件）  https://github.com/wx-minapp/minapp-vscode/blob/master/src/plugin/lib/language.ts

**Comment by qiu8310** [comment]
加 lang='wxml' 有两个目的
1：告诉 vuter 插件这不是 vue 的 html 模板 
2：minapp 支持 wxml 和 pug 两种语言，需要通过这个字段来区分

如果去掉此配置，则 vuter 和 minapp 都会提供补全。  
如果不想使用 lang，可以使用 `xlang="wxml"` 来替换。

![image](https://user-images.githubusercontent.com/1094697/50672950-f27ac300-1015-11e9-9587-6c1f00e3d853.png)

**Comment by sky-admin** [comment]
了解了，多谢。

**Comment by qiu8310** [comment]
已经发布新版本在 vscode 上了
