### ISSUE TITLE
[Bug]: 鼠标单击wxml标签导致当前文档所有相同标签被选中

### ISSUE THREAD

**Issue by wmf1993** [wx-minapp/minapp-vscode#133]
**如何复现:**
光标移动到标签上（如<text>标签），当前文档所有的<text>标签都被选中
经测试，从v2.4.2版本开始出现这个问题，v2.4.1版本正常

**期望的表现:**
正常的表现应该是，只有被选中的标签的开始和结束标签被选中

**实际的表现:**

正常：
![正常](https://user-images.githubusercontent.com/31245615/148182157-c01fcbca-31b9-4231-ae2a-addd9af75273.png)

异常：
![异常](https://user-images.githubusercontent.com/31245615/148182151-b2a3be72-7ded-4993-a133-2ff78d909c64.png)

**插件运行环境**

- `插件版本`:  v2.4.5
- `VSCode版本`: v1.62.3

**Comment by iChenLei** [comment]
@wmf1993 Thanks for report bug, I found the clue of this bug by compare [v2.4.1...v2.4.2](https://github.com/wx-minapp/minapp-vscode/compare/v2.4.1...v2.4.2). Will fix it later and release v2.4.6 .
