### ISSUE TITLE
bind:input 事件无效，只能bindinput

### ISSUE THREAD

**Issue by lmmm0013** [wx-minapp/minapp-vscode#15]
如题～

**Comment by qiu8310** [comment]
了解了

主要是我的 https://github.com/qiu8310/minapp 框架在编译的时候会自动把 bind:input 替换成 bindinput，不过你说的这个确实是个问题

**Comment by hjhwel** [comment]
一样的问题

**Comment by qiu8310** [comment]
好像之前没修好，我回头改下
