### ISSUE TITLE
[Bug]: 某个 workspace 下右键无法出现新建component和page，有的 workspace 却可以

### ISSUE THREAD

**Issue by Tuclly** [wx-minapp/minapp-vscode#172]
**如何复现:**

步骤1:
<img width="295" alt="image" src="https://github.com/wx-minapp/minapp-vscode/assets/57241074/34311072-b1c5-4465-aa0d-3ef1f5a9d2f4">
<img width="328" alt="image" src="https://github.com/wx-minapp/minapp-vscode/assets/57241074/a64478bd-37fb-4e1c-b586-f745f495f1f7">

步骤2: 

步骤3:

...

**期望的表现:**

**实际的表现:**

**插件运行环境**

- `插件版本`: 
- `VSCode版本`:
- `操作系统(非必须)`:

**Comment by iChenLei** [comment]
应该不是这个插件的功能，你是否安装了别的插件？

**Comment by Tuclly** [comment]
> 应该不是这个插件的功能，你是否安装了别的插件？

啊？这不是你们https://marketplace.visualstudio.com/items?itemName=qiu8310.minapp-vscode官网文档介绍的第一个功能吗？

**Comment by iChenLei** [comment]
是否可以列出你安装过的插件？这个feature真不是这个插件提供de
