### ISSUE TITLE
[Bug]: prettier format error: Invalid host defined options

### ISSUE THREAD

**Issue by weifeiyue** [wx-minapp/minapp-vscode#174]
**如何复现:**

更新最新prettier

...

**期望的表现:**
prettier正常

**实际的表现:**

prettier format error: Invalid host defined options

**插件运行环境**

- `插件版本`: v2.4.12
- `VSCode版本`: 1.83.0
- `操作系统(非必须)`:

**Comment by liuliangsir** [comment]
+1，具体可以看[这里](https://github.com/wx-minapp/minapp-vscode/issues/169)

**Comment by Eamon-X** [comment]
+1

**Comment by iChenLei** [comment]
应该解决了？ #185
