### ISSUE TITLE
[Bug]: 换行属性不生效，是我姿势问题吗

### ISSUE THREAD

**Issue by xiebaota** [wx-minapp/minapp-vscode#175]
**如何复现:**

步骤1:
换行属性不生效，是我姿势问题吗

步骤2: 

步骤3:

...

**期望的表现:**

**实际的表现:**

**插件运行环境**

- `插件版本`: 
- `VSCode版本`:
- `操作系统(非必须)`:

**Comment by xiebaota** [comment]
![image](https://github.com/wx-minapp/minapp-vscode/assets/27721187/fd79dacf-a7dd-48bb-8a0d-010e44bb5cbe)

**Comment by xiebaota** [comment]
![image](https://github.com/wx-minapp/minapp-vscode/assets/27721187/306aeb12-eb9f-4518-8e3a-a5b64235d3da)

**Comment by iChenLei** [comment]
@xiebaota 目前没有太多时间处理issue，抱歉，另外建议不要对自己的业务代码截图发到公网，保护自己的工作安全。

**Comment by xiebaota** [comment]
> @xiebaota 目前没有太多时间处理issue，抱歉，另外建议不要对自己的业务代码截图发到公网，保护自己的工作安全。

okok

**Comment by xiebaota** [comment]
找到问题了 "minapp-vscode.wxmlFormatter": "prettyHtml",
