### ISSUE TITLE
wxml 保留属性换行

### ISSUE THREAD

**Issue by littlee** [wx-minapp/minapp-vscode#19]
如何配置格式化 wxml 时保留属性换行
```xml
<view
  wx:if="{{true}}"
  bindtap="_tapMe"
/>
```

**Comment by qiu8310** [comment]
格式化这块当初只是一个辅助功能，没想到这个功能大家的使用量还是蛮大，我会考虑集成的

**Comment by qiu8310** [comment]
@littlee 你要求的功能 NewFuture 实现了，可以参考上面 NewFuture 提交的代码（或者在vscode配置中看最新添加的minapp-vscode开头的配置），我暂时还没写文档

**Comment by littlee** [comment]
牛逼

**Comment by NewFuture** [comment]
```jsonc
"minapp-vscode.wxmlFormatter": "prettyhtml", //指定格式化工具
"minapp-vscode.prettyHtml": {
     "wrapAttributes" : true // 属性换行
} 
```

**Comment by mxppxm** [comment]
使用prettyHtml后image标签会报错：Void elements do not have end tags "image"。应该怎么处理呢？

**Comment by NewFuture** [comment]
可以这样写
```html
<image></image>
```

**Comment by mxppxm** [comment]
向setting中添加了新的prettyhtml配置，就是这么写了，然后minapp报了这个错。

**Comment by NewFuture** [comment]
@mxppxm 

prettyHtml对image按照html5处理的 可以参考 https://github.com/wx-minapp/minapp-vscode/issues/11#issuecomment-489455718

或者 用 prettier  https://github.com/wx-minapp/minapp-vscode/issues/11#issuecomment-485762465

**Comment by NewFuture** [comment]
prettyhtml 这个PR好像是来支持image的 https://github.com/Prettyhtml/prettyhtml/pull/73

**Comment by mxppxm** [comment]
e.....不要意思，，我能问问要怎么用嘛。。不懂PR

**Comment by qiu8310** [comment]
最新版本(1.14.0)解决了 prettyhtml 格式化的问题，和 https://prettyhtml.netlify.com/ 中的格式化效果是一样的
