### ISSUE TITLE
wpy文件的支持问题

### ISSUE THREAD

**Issue by LiweiDong** [wx-minapp/minapp-vscode#21]
[让小程序支持组件化开发的框架
](https://tencent.github.io/wepy/document.html#/?id=%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE)

在wpy文件关联到wxml后 标签能补全，script和style代码无法高亮。
wpy关联到vue后 代码支持好一些，标签又不行了。。

**Comment by qiu8310** [comment]
可以支持 wepy 哦，你还是要关联到 vue, minapp 自动会处理 script 里的内容，详情看这里：

https://github.com/wx-minapp/minapp-vscode#%E5%9C%A8-vue-%E6%A8%A1%E6%9D%BF%E6%96%87%E4%BB%B6%E4%B8%AD%E4%B9%9F%E8%83%BD%E8%87%AA%E5%8A%A8%E8%A1%A5%E5%85%A8%E5%90%8C%E6%97%B6%E6%94%AF%E6%8C%81-pug-%E8%AF%AD%E8%A8%80

**Comment by legeng** [comment]
wepy 不能自动补全

**Comment by qiu8310** [comment]
@legeng 你描述下你是怎么做的，我的 vscode 上 ok

![image](https://user-images.githubusercontent.com/1094697/54525482-465b3e00-49af-11e9-95b6-fa8a3abe04bb.png)
