### ISSUE TITLE
请问wxmlFormatter怎样设置，格式化wxml时才会保留代码中间的空行？

### ISSUE THREAD

**Issue by superxiaobin** [wx-minapp/minapp-vscode#24]
请问wxmlFormatter怎样设置，格式化wxml时才会保留代码中间的空行？
那些用空行分离一段段代码的

**Comment by NewFuture** [comment]
插件的三种格式化方式都会去掉中间的空行。
如果是分割代码建议用`注释`,可能会更好
```
<view></view>
<!-- 另一部分代码分隔符  -->
<view>something else</view>
```

如果是属性换行 参照 #19

**Comment by superxiaobin** [comment]
> 插件的三种格式化方式都会去掉中间的空行。
> 如果是分割代码建议用`注释`,可能会更好
> 
> ```
> <view></view>
> 
> <view>something else</view>
> ```
> 如果是属性换行 参照 #19

> 好的，明白了，谢谢
