### ISSUE TITLE
配置了prettyHtml格式化不生效

### ISSUE THREAD

**Issue by liunewshine** [wx-minapp/minapp-vscode#28]
![image](https://user-images.githubusercontent.com/7698511/57422467-c7fa7a00-7242-11e9-9e4a-d93fe6a912f3.png)
![image](https://user-images.githubusercontent.com/7698511/57422469-caf56a80-7242-11e9-8c76-5134e257262e.png)
格式化wxml依然是原有格式，没有效果

**Comment by infinnie** [comment]
重启 VSCode 就会生效
