### ISSUE TITLE
在vue文件中按下回车就会显示vue的snippets，不管作用域在哪儿

### ISSUE THREAD

**Issue by imageslr** [wx-minapp/minapp-vscode#3]
如题，安装vetur和minapp之后，在vue文件里按下回车，即使不输入任何字符，也会显示snippet。如果卸载了minapp插件，就正常了。

更多信息在这个issue里：https://github.com/Microsoft/vscode/issues/57230

我猜是因为对wepy的支持与vetur冲突了？

**Comment by qiu8310** [comment]
上次有人提过，但我本地复现不了(也下载不了 vscode 1.26

你尝试更新下 vscode (1.27.1) 和 minapp (1.8.0) 到最新版再试试呢？

**Comment by imageslr** [comment]
目前是1.8.0 minapp 与 1.27.1 vscode，问题依然存在。

![image](https://user-images.githubusercontent.com/17822028/45348421-2c483980-b5e1-11e8-8bde-817fcd340e90.png)
![image](https://user-images.githubusercontent.com/17822028/45348433-35390b00-b5e1-11e8-9107-c3e9e0ceda0d.png)

**Comment by qiu8310** [comment]
插件确实会监听 Enter 按键，主要是给 pug 某个功能用的

不过 pug 用户应该也不多，我把这个 Enter 事件去掉吧，但我没法复现，所以我待会发个版本，到时麻烦再帮我确认下（发好了我和你说）

**Comment by qiu8310** [comment]
好了，发了一个 1.8.1 版本，把 vue 文件中的 Enter 按钮事件去掉了，你能帮我确认下有没有正常？

**Comment by qiu8310** [comment]
那就好，没想到那个 Enter 会引起这个问题，感觉还是蛮奇怪
