### ISSUE TITLE
无法给出计算属性的提示

### ISSUE THREAD

**Issue by muzea** [wx-minapp/minapp-vscode#31]
https://github.com/wx-minapp/minapp-vscode/blob/167d33c11e7c61ff942cfe960249aa0dcb96d973/src/plugin/lib/ScriptFile.ts#L15

比如 wepy 官网的这个例子
```js
  computed = {
      aPlus () {
          return this.a + 1
      }
  }
```

直接匹配 `:` 是不是太暴力了？或者加一个 `^\sPropName\s\(\s\)\s{` ？或者内置个 babel 按基本法来计算有哪些属性？

**Comment by qiu8310** [comment]
原生的小程序没有计算属性的，如果即要完全支持 wepy 或者 mpvue 或者其它小程序框架是很难的。

这个只是个辅助功能，没有打算做的很完善，如果引入 babel 难免会影响插件的性能的
