### ISSUE TITLE
emmet写法无效

### ISSUE THREAD

**Issue by davidlin88** [wx-minapp/minapp-vscode#32]
![image](https://user-images.githubusercontent.com/30857148/58342966-7aa61b80-7e84-11e9-9e60-14cd0de15938.png)
也无法弹出组件的智能补全，不知道二者是否有关联

版本: 1.13.3
vscode版本：1.34.0 macOS

**Comment by kaierrao** [comment]
+1

**Comment by qiu8310** [comment]
你文件的格式不是 wxml 吧，要看 vscode 右下角

**Comment by qiu8310** [comment]
![image](https://user-images.githubusercontent.com/1094697/58368889-acbb8a00-7f25-11e9-81be-e89eaa079fe7.png)

**Comment by davidlin88** [comment]
> 你文件的格式不是 wxml 吧，要看 vscode 右下角

是wxml的，为了防止setting的干扰全部注释了也没有emmet

**Comment by qiu8310** [comment]
仔细看了下你的截图，tag 自动补全需要输入 "<" 之后才会触发


![image](https://user-images.githubusercontent.com/1094697/58376987-9a832f80-7fa9-11e9-9f2c-2a137723c763.png)

**Comment by qiu8310** [comment]
emmet 的自动补全不是 minapp 插件实现的，而是 minapp 会在你的 user 配置文件中写入一个配置项

```
  "emmet.includeLanguages": {
    "wxml": "html"
  },
```

如果这个配置项没有，或者被删除了，那 emmet 也就没有了，你自己可以检查下，或者手动加上

**Comment by qiu8310** [comment]
希望对你有帮助

**Comment by davidlin88** [comment]
> emmet 的自动补全不是 minapp 插件实现的，而是 minapp 会在你的 user 配置文件中写入一个配置项
> 
> ```
>   "emmet.includeLanguages": {
>     "wxml": "html"
>   },
> ```
> 
> 如果这个配置项没有，或者被删除了，那 emmet 也就没有了，你自己可以检查下，或者手动加上

哦天 感谢 非常很帮助 相信能提高以后的开发速度，插件很赞👍
