### ISSUE TITLE
wxml 中 style 会自动换行导致编译报错

### ISSUE THREAD

**Issue by Hansuku** [wx-minapp/minapp-vscode#48]
![image](https://user-images.githubusercontent.com/28286561/61778784-fd6e3700-ae31-11e9-8c48-0bc568ea8787.png)
像这种本身不应该换行的 这样换行了开发者工具会直接报错

**Comment by qiu8310** [comment]
你用的是什么格式化配置，即配置项 minapp-vscode.wxmlFormatter 的值是什么

**Comment by qiu8310** [comment]
我猜这应该是你使用的格式化工具自动格式化导致的，你可以修改格式化工具的配置，或者换一个格式化工具，或者不要配置自动格式化

**Comment by NewFuture** [comment]
prettier 可以加个注释跳过自动格式化
```html
<!-- prettier-ignore-attribute style -->
```

reference https://github.com/NewFuture/miniprogram-template/issues/40
