### ISSUE TITLE
vscode中wxml格式化选prettier后会对代码中注释报错

### ISSUE THREAD

**Issue by whswhs9126** [wx-minapp/minapp-vscode#50]
配置
"minapp-vscode.wxmlFormatter": "prettier"
报错
prettier format error: Unexpected token (1:1) > 1 |  | ^ 2 | <view class="index-page"> 3 |  4 | <view class="header">

**Comment by qiu8310** [comment]
方便发下你要格式的那部分 wxml 代码么（或者是最小的会引起报错的那部分代码）

**Comment by whswhs9126** [comment]
小程序初始化demo
```
<!--index.wxml-->
<view class="container">
  <view class="userinfo">
    <button wx:if="{{!hasUserInfo && canIUse}}" open-type="getUserInfo" bindgetuserinfo="getUserInfo"> 获取头像昵称 </button>
    <block wx:else>
      <image bindtap="bindViewTap" class="userinfo-avatar" src="{{userInfo.avatarUrl}}" mode="cover"></image>
      <text class="userinfo-nickname">{{userInfo.nickName}}</text>
    </block>
  </view>
  <view class="usermotto">
    <text class="user-motto">{{motto}}</text>
  </view>
</view>
```

**Comment by qiu8310** [comment]
```json
{
  "minapp-vscode.wxmlFormatter": "prettier",
  "minapp-vscode.prettier": {
    "parser": "html"
  }
}
```

要手动指定 prettier 的 parser，我下个版本里配置成默认的吧

**Comment by whswhs9126** [comment]
谢了

**Comment by wfnian** [comment]
> ```json
> {
>   "minapp-vscode.wxmlFormatter": "prettier",
>   "minapp-vscode.prettier": {
>     "parser": "html"
>   }
> }
> ```
> 
> 要手动指定 prettier 的 parser，我下个版本里配置成默认的吧

可是这样设置的话如果在wxml文件粘贴一个单词的话他会额外多出一个换行符（我已经确认了没有复制换行），不知是和其他插件冲突还是
