### ISSUE TITLE
支持语言自定义配置

### ISSUE THREAD

**Issue by chenjigeng** [wx-minapp/minapp-vscode#51]
存在一些情况，是通过jsx的方式来写wxml的。这个时候，我就预期在jsx/js文件里，也可以使用这个插件的自动补全功能，可是目前是不支持的。想问下是不是支持语言自定义配置？

**Comment by iChenLei** [comment]
Taro ? 如果是jsx写wxml, 是不是可以通过声明 *.d.ts 来实现代码补全提示？
> 题外话: 你现在应该不写小程序了，看你的github个人主页蛮想认识你的，可以加个好友认识一下吗？ 我微信号: Ochenlei

**Comment by iChenLei** [comment]
Taro ? 如果是jsx写wxml, 是不是可以通过声明 *.d.ts 来实现代码补全提示？
