### ISSUE TITLE
名称要不要改成Miniapp？

### ISSUE THREAD

**Issue by firevenus** [wx-minapp/minapp-vscode#54]
我看这个插件是VS Code里小程序插件下载量最大的了，但是感觉叫Minapp怪怪的啊，要不要把名称改成Miniapp？

**Comment by qiu8310** [comment]
minapp 是我之前一个小程序框架（没怎么维护了）的名称，沿用过来的，vscode 插件的话大家应该也不会关注插件名称吧 哈哈

mini app 可能也会怪，因为微信叫它的小程序是 mini program
