### ISSUE TITLE
怎么自己设置wxml高亮颜色呢

### ISSUE THREAD

**Issue by mipawn** [wx-minapp/minapp-vscode#55]
没修改的蓝色看到我眼睛疼，想换个颜色，请问怎么修改呢。
![image](https://user-images.githubusercontent.com/39559813/67365102-887eda80-f5a3-11e9-8012-16fffdd02910.png)

**Comment by qiu8310** [comment]
那是根据你的主题颜色设置的，你可以切换 vscode 的主题

或者你可以将配置项 "minapp-vscode.disableDecorate" 设置成 false；同时在 "minapp-vscode.decorateType" 配置中设置你想要的颜色

**Comment by dongbusi** [comment]
> 那是根据你的主题颜色设置的，你可以切换vscode的主题
> 
> 或者你可以将配置项“ minapp-vscode.disableDecorate”设置成false；同时在“ minapp-vscode.decorateType”配置中设置你想要的颜色

是在setting.json来设置么？

**Comment by qiu8310** [comment]
是的
