### ISSUE TITLE
格式化问题闹心几天呀，作者能帮忙解决么

### ISSUE THREAD

**Issue by Alexwsc** [wx-minapp/minapp-vscode#57]
直接上图吧
![格式化问题](https://user-images.githubusercontent.com/15664780/67952521-654dce00-fc28-11e9-81e0-a255e566280c.png)
我的VSCode的setting.json设置如下图
![格式化问题2](https://user-images.githubusercontent.com/15664780/67952679-9e863e00-fc28-11e9-8f13-f08f8aea83fa.png)
![格式化问题3](https://user-images.githubusercontent.com/15664780/67952760-c2e21a80-fc28-11e9-808b-1d408813eeb5.png)
安装的插件有minapp、ESLint、prettier、Vetur等相关的小程序开发的插件，现在遇到的问题是，我格式化图1的wxml文件，vscode出现下面的问题
![格式化问题4](https://user-images.githubusercontent.com/15664780/67953032-4a2f8e00-fc29-11e9-8f68-d3ab9e51e8d0.png)
右键格式化选择格式化方法操作如下
![格式化问题5](https://user-images.githubusercontent.com/15664780/67953108-75b27880-fc29-11e9-8294-eb4a2a49fd43.png)
![格式化问题6](https://user-images.githubusercontent.com/15664780/67953191-a0043600-fc29-11e9-9304-67382e2650db.png)

**Comment by qiu8310** [comment]
一直忘记改默认值，你看这里 https://github.com/wx-minapp/minapp-vscode/issues/50#issuecomment-518482194

**Comment by Alexwsc** [comment]
哎，一行代码的事，还是怪自己没看清使用文档。
