### ISSUE TITLE
格式化标签内的内容是否可以设置不换行？

### ISSUE THREAD

**Issue by smallk2012** [wx-minapp/minapp-vscode#59]
问题：

`<view class="tag">`
 `     {{item.a}}`
`</view>`
`<text class="tag">`
`      {{item.b}}`
`</text >`
期望：
`<view class="tag">{{item.a}}</view>`
`<text class="tag">{{item.b}}</text >`

**Comment by qiu8310** [comment]
插件支持三种不同的 format（默认的、prettyhtml、prettier）工具，你可以参考 https://github.com/wx-minapp/minapp-vscode/pull/23 这里看下
