### ISSUE TITLE
在wxml中格式化的时候出现换行符变成auto的情况是怎么回事？

### ISSUE THREAD

**Issue by sjlei** [wx-minapp/minapp-vscode#6]
直接上图

![default](https://user-images.githubusercontent.com/34293221/48386184-1ca5b800-e72c-11e8-8e63-673e5d754290.gif)

似乎是更新到vscode的最新版本之后发生的这种情况，更新之前是没有的，但是不知道该如何解决。

> **VSCode版本**
> 版本: 1.29.0 (user setup)
> 提交: 5f24c93878bd4bc645a4a17c620e2487b11005f9
> 日期: 2018-11-12T07:47:15.448Z
> Electron: 2.0.12
> Chrome: 61.0.3163.100
> Node.js: 8.9.3
> V8: 6.1.534.41
> 架构: x64

其他文件没有此问题，禁用掉minapp拓展也没有问题，应该是新版本更新的内容起冲突了吗？

**Comment by qiu8310** [comment]
解释下，vscode 中有个配置项叫 `files.eol`，插件在格式化时需要获取这个配置（保持换行符的统一），但 vscode 这个最新版本会直接返回原生的配置项 `auto` 给我，以前返回的时转化后的配置（如 `\n` 或 `\r\n`），所以就导致了所有换行符都是 `auto` 的问题

**Comment by sjlei** [comment]
赞！问题解决了！
