### ISSUE TITLE
关于image标签导致不能格式化的问题

### ISSUE THREAD

**Issue by ZXMLoveCXF** [wx-minapp/minapp-vscode#60]
prettyHtml format error: Void elements do not have end tags "image"

这样提示  有什么办法能解决吗？

配置是这样的
```json
   { 
"minapp-vscode.wxmlFormatter":"prettyHtml",
    "minapp-vscode.prettyHtml":{
        "printwidth": 100,
        "singLeQuote": false,
        "usePrettier": true,
        "wrapAttributes": true,
        "sortAttributes": true
    }
}
```

**Comment by NewFuture** [comment]
这么写`<image></image>`

**Comment by ZXMLoveCXF** [comment]
> 这么写`<image></image>`

除了这个没有别的办法？

**Comment by juvham** [comment]
现在是这么写<image></image>
会报 
prettyHtml format error: Void elements do not have end tags "image"

<image /> 就不会
这两者不能并存么
