### ISSUE TITLE
代码提示一直西显示正在加载...

### ISSUE THREAD

**Issue by frei-x** [wx-minapp/minapp-vscode#62]
WARN 在 1750ms 后终止了 onWillSaveTextDocument 事件
卸载minapp就没问题

**Comment by qiu8310** [comment]
可能是一个 bug，你在编辑哪个文件的时候会这样，方便把那个文件贴一下么

**Comment by frei-x** [comment]
@qiu8310 

> 可能是一个 bug，你在编辑哪个文件的时候会这样，方便把那个文件贴一下么

可以了,我把  ''格式化时，单行允许的最长的长度(只针对默认的格式化工具)'' 调大就好了
[相关问题](https://github.com/microsoft/vscode/issues/41194)

> Seeing the same thing with the vscode-go plugin which recently switched over to this logic with that hard limit. This totally must be configurable.

**Comment by frei-x** [comment]
单行代码太长的时候,还是经常会出现 "vscode 正在运行保存参与程序" @qiu8310

**Comment by iChenLei** [comment]
closed via https://github.com/wx-minapp/minapp-vscode/pull/125
