### ISSUE TITLE
请问你截图中 Ts 中用的库什么？

### ISSUE THREAD

**Issue by John0King** [wx-minapp/minapp-vscode#7]
![示例图片](https://n1image.hjfile.cn/res7/2018/11/20/c8d41ef5bce1b2128bb7a830d06338b9.gif)

```typescript
@pagefy()
export class Index extend xxxx{}
```

我目前正在搞一个类似的 运行时， https://github.com/John0King/typed-we-app/blob/typescript-runtime/runtimeSample/pages/index/index.ts ， 正好可以借鉴一下

**Comment by qiu8310** [comment]
我年初的时候写的一个工具  https://github.com/qiu8310/minapp

**Comment by John0King** [comment]
@qiu8310 你是在 declarator  里面 执行 初始化 Page 等对象  👍 。
