### ISSUE TITLE
如何配置格式化wxml时不自动去除空行？

### ISSUE THREAD

**Issue by wangzl1163** [wx-minapp/minapp-vscode#72]
在格式化wxml时会自动去除空行，如何配置才能不自动去除呢？

**Comment by June-elisa** [comment]
我也想知道  没有空行看着好难受

**Comment by iChenLei** [comment]
可以看一下 prettier / pretty-html有没有相关配置，如果有配置但是minapp-vscode没支持可以再提issue处理，谢谢

**Comment by dingsp** [comment]
确实，怎么不自动去除空行

**Comment by wangzl1163** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
