### ISSUE TITLE
请问如何关闭在js中提示样式类名

### ISSUE THREAD

**Issue by shuwanghu** [wx-minapp/minapp-vscode#74]
![image](https://user-images.githubusercontent.com/32955341/84145246-215b5b00-aa8c-11ea-89e1-86d471fc0c67.png)

**Comment by shuwanghu** [comment]
顺带问一下有没有交流群，这样的话大家可以交流经验

**Comment by qiu8310** [comment]
是纯 JS 文件还是 VUE 文件，纯 JS 文件的话应该是其它插件做的补全

**Comment by qiu8310** [comment]
> 顺带问一下有没有交流群，这样的话大家可以交流经验

没有交流群，用的人应该也不多

**Comment by shuwanghu** [comment]
纯的js文件，用的人很多了228751次下载啊老哥，搞个交流群吧，这个项目感觉很有前景的

**Comment by shuwanghu** [comment]
老哥，我感觉你这个已经是最好用的小程序的插件了，要搞下去啊兄弟

**Comment by qiu8310** [comment]
> 纯的js文件

那你禁用一个可能的插件试试，应该是某些插件注入的补全，禁用它（或修改配置）就可以

> 用的人很多了228751次下载啊老哥，搞个交流群吧，这个项目感觉很有前景的

有你这句话我得优化下了 哈哈 （关键是想做的东西太多，时间太少了）

**Comment by shuwanghu** [comment]
我已经搞定了，加油老哥啊，能不能早点下班就看你的了
话说你不找人一起弄吗？一个人会有点无聊了，多找几个人一起搞啊

**Comment by iChenLei** [comment]
@shuwanghu 目前我开始接手维护，有问题可以提issue @ 我
