### ISSUE TITLE
wx的 API没有提示

### ISSUE THREAD

**Issue by qq121492187** [wx-minapp/minapp-vscode#8]
我安装好插件后 在JS文件用wx的api ，没有提示，需要怎么配置？

**Comment by JavenZ** [comment]
老哥怎么解决的？

**Comment by JavenZ** [comment]
@qq121492187 @qiu8310 这个问题有解法吗？我在js文件里想写wx.showToast()但是没有提示

**Comment by qiu8310** [comment]
@JavenZ 这不是 vscode 插件做的，参考 https://github.com/wx-minapp/minapp-example-custom-wx 这里
