### ISSUE TITLE
使用了prettier 或者 prettyHtml 格式化 保存时就会报错

### ISSUE THREAD

**Issue by smalldice** [wx-minapp/minapp-vscode#83]
编辑器配置：
{
"minapp-vscode.wxmlFormatter": "prettier",
  "minapp-vscode.prettier": {
    "parser": "html",
    "singleQuote": false
  }
}

**Comment by smalldice** [comment]
报错内容
prettier format error: Unexpected closing tag "text". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (26:104)
  24 |           <view class='wrong-words'>
  25 |             <text class='label'>易读错字：</text>
> 26 |             <text class='words {{ wrongWords.length === 0 ? 'no-word' : '' }}'>{{ wrongWords || '暂无' }}</text>
     |                                                                                                        ^^^^^^^
  27 |           </view>
  28 |           <ky-button type='primary' data-name='班级报告' classes='class-report-btn' disabled='{{ !hasResult }}' bindtap='goToClassReport'>班级报告</ky-button>
  29 |         </view>

**Comment by gz227** [comment]
> 报错内容
> prettier format error: Unexpected closing tag "text". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (26:104)
> 24 |
> 25 | 易读错字：
> 
> > 26 |             <text class='words {{ wrongWords.length === 0 ? 'no-word' : '' }}'>{{ wrongWords || '暂无' }}
> > |                                                                                                        ^^^^^^^
> > 27 |           
> > 28 |           班级报告
> > 29 |

我也遇到了，请问最后怎么解决的呢

**Comment by June-elisa** [comment]
我也遇到了

**Comment by iChenLei** [comment]
prettier/prettyHtml的格式化是针对标准HTML, wxml里不少标签和标准HTML不一样，所以会有一些问题

**Comment by Gusiil** [comment]
退到 2.1 版本就没问题。。

**Comment by iChenLei** [comment]
@Gusiil 能具体说一下什么版本有问题，没问题的版版本是2.1.0吗？ 这里可能涉及到插件打包的prettier版本的问题

**Comment by JunVincetHuo** [comment]
我也遇到了，请问怎么解决

**Comment by iChenLei** [comment]
@JunVincetHuo  prettier/prettyHtml 不支持多root的wxml文件，目前我在计划写专门的 wxml-parser来支持format

**Comment by JserWang** [comment]
@iChenLei 请问能提供个属性来禁用`wxml`的格式化么？在wxml中增加了一部分yaml的内容，自动格式化会导致`yaml`格式出现问题，导致在解析`yaml`代码块中的内容时由于格式化后的错乱导致出现解析问题。 或者在使用`prettier`时，允许`.prettierignore`相关的配置生效。

**Comment by iChenLei** [comment]
@JserWang 格式化是手动的功能，不使用就可以吧？ 可以提供具体的代码样例吗

**Comment by JserWang** [comment]
> @JserWang 格式化是手动的功能，不使用就可以吧？ 可以提供具体的代码样例吗

```html
<route lang="yaml">
meta:
  requiresLogin: true
</route>
<view>test</view>
```

当我在vscode编辑完保存之后，代码会变成
```html
<route lang="yaml">meta:
  requiresLogin: true</route>
<view>test</view>
```
我的编译工具会解析`<route>`标签中的`yaml`内容来自动配置路由相关信息后将其移除，目前由于格式化导致`yaml`格式出现了问题。

我的vscode中有一项配置为`"editor.formatOnSave": true,`，我想大多数开发者应该都会默认打开这一项配置。但是目前使用这个插件后会对我的文件造成破坏性的影响。在没加入`wxmlFormatter`的版本之前，插件不会对我的`wxml`进行任何变更，所以我希望能提供一个配置开关来禁用`wxmlFormatter`

**Comment by iChenLei** [comment]
@JserWang 了解了，这两天释出一个加format开关的版本，感谢反馈
目前麻烦你要么 `1.关闭自动forma`t 或者 `2.暂时回退到老版本吧 `

**Comment by JserWang** [comment]
> @JserWang 了解了，这两天释出一个加format开关的版本，感谢反馈 目前麻烦你要么 `1.关闭自动format` 或者 `2.暂时回退到插件老版本吧 `

@iChenLei thx a lot.

**Comment by iChenLei** [comment]
@JserWang v2.4.0 即将发布
![minapp-disable-format](https://user-images.githubusercontent.com/14012511/140061074-e7882f01-7d01-4b8f-ac79-472c011a5768.gif)
> 顺便说一句下一次请单独提issue，谢谢合作，有钉钉账号的话可以加到README.md里的钉钉，可以实时答疑
