### ISSUE TITLE
不知道什么原因导致的、总是没有效果啊

### ISSUE THREAD

**Issue by shadow-boy** [wx-minapp/minapp-vscode#9]
你好、非常感谢贡献这个插件啊哈、但是不知道为什么我安装了这个插件总是感觉没有效果啊、也重启过很多次了还是没有效果、难道是跟系统有关系吗、我用的macos系统

**Comment by qiu8310** [comment]
![image](https://user-images.githubusercontent.com/1094697/49728368-82467f00-fcad-11e8-8256-95dd286c3820.png)

看 vscode 的右下角处的语言是不是 wxml，另外确保禁用了其它 wxml 的插件

**Comment by shadow-boy** [comment]
> ![image](https://user-images.githubusercontent.com/1094697/49728368-82467f00-fcad-11e8-8256-95dd286c3820.png)
> 
> 看 vscode 的右下角处的语言是不是 wxml，另外确保禁用了其它 wxml 的插件

好的、谢谢哈、就是因为这个原因，我之前是html的、因为这个折腾了一下午了、太感谢了

**Comment by zzhhbyt1** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/1094697/49728368-82467f00-fcad-11e8-8256-95dd286c3820.png)
> > 看 vscode 的右下角处的语言是不是 wxml，另外确保禁用了其它 wxml 的插件
> 
> 好的、谢谢哈、就是因为这个原因，我之前是html的、因为这个折腾了一下午了、太感谢了

一般来说，如果由谁确定issue已解决，就由谁来close掉issue。不close会造成杂乱。
